# Generated by Django 2.1.7 on 2019-03-12 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0009_auto_20190312_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 15, 44, 38, 664760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 12, 15, 44, 38, 665110, tzinfo=utc)),
        ),
    ]
