# Generated by Django 2.1.7 on 2019-03-13 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0011_auto_20190313_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 3, 3, 3, 981531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 3, 3, 3, 983433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 3, 3, 3, 981905, tzinfo=utc)),
        ),
    ]
