# Generated by Django 2.1.7 on 2019-03-13 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0014_auto_20190313_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='portrait',
            field=models.ImageField(default='pic_folder/portrait/no-img.jpg', upload_to='pic_folder/portrait/'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 6, 13, 18, 995156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 6, 13, 18, 999209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 6, 13, 18, 996061, tzinfo=utc)),
        ),
    ]
