# Generated by Django 2.1.7 on 2019-03-13 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0015_auto_20190313_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 6, 36, 21, 191809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actor',
            name='portrait',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/portrait/'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 6, 36, 21, 195579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 6, 36, 21, 192681, tzinfo=utc)),
        ),
    ]
