# Generated by Django 2.1.7 on 2019-03-13 08:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intekimdb', '0016_auto_20190313_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_comment', models.TextField(blank=True, max_length=160)),
                ('object_id', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 18, 37, 189890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actor',
            name='portrait',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/portrait'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 18, 37, 191898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 18, 37, 190372, tzinfo=utc)),
        ),
    ]
