# Generated by Django 2.1.7 on 2019-03-13 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0017_auto_20190313_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 19, 58, 545214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 19, 58, 548545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 19, 58, 546070, tzinfo=utc)),
        ),
    ]
