# Generated by Django 2.1.7 on 2019-03-13 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0018_auto_20190313_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 20, 27, 681606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 20, 27, 683647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 20, 27, 682087, tzinfo=utc)),
        ),
    ]
