# Generated by Django 2.1.7 on 2019-03-13 15:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0025_auto_20190313_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 3, 29, 869631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 3, 29, 870327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 3, 29, 872315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 3, 29, 870784, tzinfo=utc)),
        ),
    ]
