# Generated by Django 2.1.7 on 2019-03-13 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0026_auto_20190313_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 38, 16, 738349, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 38, 16, 740505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 38, 16, 737557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 15, 38, 16, 738844, tzinfo=utc)),
        ),
    ]
