# Generated by Django 2.1.7 on 2019-03-14 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0027_auto_20190314_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 3, 3, 33, 560717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 3, 3, 33, 562898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 3, 3, 33, 559938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 3, 3, 33, 561183, tzinfo=utc)),
        ),
    ]
