# Generated by Django 2.1.7 on 2019-03-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0027_auto_20190313_2238'),
        ('intekimdb', '0029_auto_20190314_1037'),
    ]

    operations = [
    ]
