# Generated by Django 2.1.7 on 2019-03-14 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0030_merge_20190314_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 8, 36, 10, 173472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 8, 36, 10, 175574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 8, 36, 10, 172707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 8, 36, 10, 174027, tzinfo=utc)),
        ),
    ]
